# Generated by Django 6.0.2 on 2026-04-08 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_items', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(upload_to='items_photo')),
                ('item_title', models.CharField(max_length=100)),
                ('item_discription', models.TextField(blank=True, null=True)),
                ('item_added_time', models.DateTimeField(auto_now_add=True)),
                ('item_is_sold', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items_app.producttype')),
            ],
        ),
    ]
